[package]
name = "gost732-2017"
version = "0.1.1"
entrypoint = "g7.32-2017.typ"
authors = [
    "vzalygin <https://github.com/vzalygin",
    "pluttan <https://github.com/pluttan>"
]
license = "MIT"
description = "Styles to format docs with GOST 7.32-2017"
repository = "https://github.com/bmstudents-dev-group/typst-g7.32-2017"
keywords = ["gost7.32-2017", "gost"]
categories = ["text", "scripting"]
